### ISSUE TITLE
Reproducible build failed

### ISSUE THREAD

**Issue by linsui** [NimaKhajehpour/TaskManager#8]
https://gitlab.com/fdroid/fdroiddata/-/jobs/3678209116

Which jdk version is used?

**Comment by NimaKhajehpour** [comment]
@linsui Hey so the jdk is 1.8 (the same as the first version that had RB). but the app has 3 versions now and do you think the reason it stopped is that it got two last versions mixed up?

**Comment by NimaKhajehpour** [comment]
also i think wikianime has failed too :disappointed:

**Comment by linsui** [comment]
I guess that's because we build it with jdk 11. The diff only shows different Ldalvik/annotation/MethodParameters. Could you please build it with jdk 11?

**Comment by NimaKhajehpour** [comment]
@linsui i releases the latest version built with jdk 11. the other build is not that important since it had the least amount of changes and all the changes are in the v1.1.1. so maybe i can just delete v1.1 tag and we go for build on v1.1.1?

**Comment by linsui** [comment]
Yes, it's up to you. I'll test v1.1.1. Thanks!

**Comment by NimaKhajehpour** [comment]
Thanks so i deleted v1.1 we can go with the latest. I also updated wikianime to jdk 11 since it had the same issue.

**Comment by linsui** [comment]
Both are fixed, thanks!

**Comment by obfusk** [comment]
> Hey so the jdk is 1.8

The Android Gradle plugin version you're using requires Java 11 to run, so that can't be correct.

**Comment by linsui** [comment]
Maybe the jdk used to run gradle is 11 but the jdk used to build the code is 8.

**Comment by obfusk** [comment]
> Maybe the jdk used to run gradle is 11 but the jdk used to build the code is 8.

Unless you explicitly define a different [toolchain](https://docs.gradle.org/current/userguide/toolchains.html#toolchains) (which I see no evidence of here), Gradle "uses the same Java version for running Gradle itself and building JVM projects".

Note that [`sourceCompatibility`/`targetCompatibility`](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation) are about "which language version of Java your source files should be treated as" and "the version of byte code the compiler generates", not which JDK version is used to compile the project (though obviously you can't compile it with a lower version than used in those options).

**Comment by linsui** [comment]
The jdk used to compile the java code can be set with `-Dorg.gradle.java.home`. Maybe AS does that.

**Comment by obfusk** [comment]
> Maybe AS does that.

I suppose it *could* do that. But why would it?

You can change the JDK in the gradle settings in AS; AFAIK that uses the same JDK for Gradle itself and the build and there does not appear to be a setting to tell it to use a different one for each of those.

**Comment by NimaKhajehpour** [comment]
> The Android Gradle plugin version you're using requires Java 11 to run, so that can't be correct.

@obfusk  i have always had my JDK to 1.8. other projects if you  see them in my jdk my java target and java build version in my build gradle is 1.8. so its weird that the gradle needs jdk 11 but can use 1.8. and the other thing is that my other apps got built with RB and jdk 1.8.

**Comment by NimaKhajehpour** [comment]
but is RB working now? or is there still a problem?

**Comment by linsui** [comment]
It works now. But we don't know why it works. ;)

**Comment by NimaKhajehpour** [comment]
so the problem mainly should not be the jdk then?

**Comment by NimaKhajehpour** [comment]
actually now that i have seen the AS setting on gradle, the gradle jdk version is set to 11.0.13 which means that the changes i did in the commit to gradle did not change anything. (which @obfusk said that it should not affect for `source` and `target` compatibility) so it is weird.

**Comment by obfusk** [comment]
> so the problem mainly should not be the jdk then?

We're not sure. Something about the annotations in the generated `.dex` bytecode is different.

See https://gitlab.com/fdroid/fdroiddata/-/issues/2816#note_1258419526

Which almost certainly means something different about the tool(s) used to generate that bytecode during the build on your end (this really doesn't look like an ordering difference -- like the `.profm` -- or something else that might differ between different builds even if they use the exact same versions of all build tools).

The JDK version seems like a likely candidate (since we often -- but not always -- see annotation differences when using e.g. OpenJDK 11 for one build and 17 for another), but we don't really have enough information at this time.

And unlike e.g. the version of the Android Gradle plugin etc., which should be stored in the git repo, the JDK version you used to build your APK is not something we can know without you telling us.

So we're hoping you can tell us if anything may have changed on your end :)

**Comment by NimaKhajehpour** [comment]
@obfusk so the JDK actually was the jdk 11 (the AS default one) which did not change anything on the build jdk version when i changed the target in gradle, and the last changes i did on the code i got the release. can it be the corretto you talked about? since  i'm using the default jdk 11? because for both wikianime and taskmanager i did not have any big changes on the code and the latest updates were built and i got release out of it.

**Comment by NimaKhajehpour** [comment]
if the problem persists maybe i can use openJDK11 that i have (other than AS default jkd 11) and see that could solve the problem?
and for the GitLab issue i am actually following that to see what can help or what is the problem. and if you think it can be the jdk, the only thing i can think of is that AS default jdk

**Comment by NimaKhajehpour** [comment]
@obfusk another thing i realized from the outputs that you got on here: https://gitlab.com/fdroid/fdroiddata/-/issues/2816#note_1258419526

for task manager it is talking about the generated code from hilt which is used to generate singleton instances of my database and let me inject my classes. it seems like it sees a addition to my `note` and `task` data models which i did change but the change was minimal (just making a field optional) and should not change anything since i build it with that change, but do you think `Dagger/Hilt` or the change on my database could cause the difference?

another thing is that the log you have sent is talking about values (`val`) on the `note` and `task` which both of them have just one and its a random `UUID` generated by the code. the other field are variables (`var`)

**Comment by obfusk** [comment]
> and for the GitLab issue i am actually following that to see what can help or what is the problem

Thanks :)

> maybe i can use openJDK11 that i have (other than AS default jkd 11) and see that could solve the problem?

Currently, the problem seems to be gone. I would advise always using OpenJDK 11 to avoid any potential problems with different JDK implementations behaving differently, but I have no idea whether that's likely to happen or relevant here.

**Comment by obfusk** [comment]
Looking a bit closer, the differences in the dalvik annotations in the `.dex` which caused the RB to fail seem to be the result of the `suspend fun`s in [`TaskDao.kt`](https://github.com/NimaKhajehpour/TaskManager/blob/main/app/src/main/java/com/nima/taskmanager/data/TaskDao.kt) generating code with slightly different parameter names (`arg1` vs `continuation`).

I'm not sure whether that's related to the JVM used, but assuming that all builds used the same libraries and build tools (which they should, as those should be defined in the repo, unlike the JVM), I'm not sure what else it could be.

I suppose it could a bug in the kotlin libraries that somehow got triggered on your end only. Our CI builds seem to produce the same annotations consistently, even with OpenJDK 17 (though using that causes other changes). But that seems less likely,

**Comment by NimaKhajehpour** [comment]
> I would advise always using OpenJDK 11 to avoid any potential problems with different JDK implementations behaving differently

yeah i will change it to OpenJDK and wont be using the default one anymore. I saw that both projects got built and no problems with RB either. I will keep looking for causes, if it was only the TaskManager i would say that it might have been something with `Dagger/Hilt` and the way they generated the codes with different JDKs. but it does not make any sense since the other project did not have `Dgger/Hilt`. Anyways thanks for the help on solving the problem on RB and i will look around more and if i find out anything i let you guys know :heart:

**Comment by obfusk** [comment]
I'm not sure whether this is at all relevant, but I noticed that your WikiAnime APKs are all signed using `signflinger` (so clearly built using Android Studio or using a Gradle signing config), whereas your TaskManager APKs are not.

So clearly you're using a different method to generate signed APKs for these apps.

This is not a problem, as long as it's intentional. But if you're not aware of anything that would explain these differences, it may indicate something odd is happening on your end.

**Comment by NimaKhajehpour** [comment]
> Looking a bit closer, the differences in the dalvik annotations in the .dex which caused the RB to fail seem to be the result of the suspend funs in [TaskDao.kt](https://github.com/NimaKhajehpour/TaskManager/blob/main/app/src/main/java/com/nima/taskmanager/data/TaskDao.kt) generating code with slightly different para

Yupp i saw that this morning and thought i would see the generated files from `Dagger` tha made my `Room` database and my `Dao`. it seemed strange that it is using `arg` instead of `continuation` because after even reverting the changes that i made on the compatibility option on jdk it was generating my `Dao` with the same structure and both jdk 11 and 1.8 had continuation, so i would say it might be a bug since it did not generate different structure on my end.

> I'm not sure whether this is at all relevant, but I noticed that your WikiAnime APKs are all signed using signflinger (so clearly built using Android Studio or using a Gradle signing config), whereas your TaskManager APKs are not.

well that is weird since i am using the same method for generating my keys and signing my APKs for every project. which is all done using android studio itself. I dont know why would that be the case. so if TaskManager was not signed using `signflinger` what could it be?

**Comment by obfusk** [comment]
> if TaskManager was not signed using `signflinger` what could it be?

My mistake. It probably was.

It's just not identifiable as being signed with `signflinger` b/c it doesn't have a v1 signature.

That does still leaves a difference: WikiAnime has a v1 + v2 signature, and TaskManager only a v2.

```
$ apksigner verify -v WikiAnime-1.0.1-jdk11.apk | grep -v ^WARNING:
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
$ apksigner verify -v TaskManager-v1.1.1-jdk11.apk
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
```

**Comment by NimaKhajehpour** [comment]
yeah i saw that when i got the RB fail while i was reviewing the errors and i noticed the difference on the scheme on both projects and i actually dont know why it would be like that, do you think it has something to do with target SDK? TaskManager is built with target SDK of 32 and other projects are 33

**Comment by obfusk** [comment]
> do you think it has something to do with target SDK? TaskManager is built with target SDK of 31 and other projects are 33

Actually, it's probably the `minSdk 21` vs `minSdk 24`; v2 signatures were introduced with Android 7.0 (API level 24), so v1 is not needed if minSDK is 24 or higher.

**Comment by NimaKhajehpour** [comment]
[this](https://stackoverflow.com/questions/59593322/cant-use-signature-scheme-v1-v2-simultaneously) post says that it has something to do with min SDK and it does check out the min SDK on WikiAnime is 21 and TaskManager is 24

**Comment by NimaKhajehpour** [comment]
> it's probably the minSdk 21 vs minSdk 24

Yupp checks out :smile:  so we got that solved, yet no clear answer for the cause of difference on `.dex` files

**Comment by obfusk** [comment]
> no clear answer for the cause of difference on .dex files

Unfortunately not. But thanks for helping us look into it.

**Comment by NimaKhajehpour** [comment]
of course whatever helps you to solve/identify problems specially for RB.  Sadly i could not help with this one but if i see anything related i'll let you know. thank you @linsui and @obfusk and all other behind the scenes members for helping solve the problems :heart:
